/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab7_josephmoscoso;

import java.util.ArrayList;
import java.util.Collections;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Joseph
 */
public class principal extends javax.swing.JFrame {

    /**
     * Creates new form principal
     */
    public principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_registrar = new javax.swing.JDialog();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        reg_nombre = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        sp_edad = new javax.swing.JSpinner();
        bt_m = new javax.swing.JRadioButton();
        bt_f = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        reg_usuario = new javax.swing.JTextField();
        reg_contraseña = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta_descripcion = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        bg_si = new javax.swing.JRadioButton();
        bg_no = new javax.swing.JRadioButton();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ta_intereses = new javax.swing.JTextArea();
        bt_registrar = new javax.swing.JButton();
        bt_sexo = new javax.swing.ButtonGroup();
        bg_premium = new javax.swing.ButtonGroup();
        jd_usuario = new javax.swing.JDialog();
        jLabel14 = new javax.swing.JLabel();
        tab = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        mostrarn = new javax.swing.JTextField();
        mostrare = new javax.swing.JTextField();
        mostrars = new javax.swing.JTextField();
        mostraru = new javax.swing.JTextField();
        mostrarc = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        mostrari = new javax.swing.JTextArea();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        mostrard = new javax.swing.JTextArea();
        jLabel22 = new javax.swing.JLabel();
        mostrart = new javax.swing.JTextField();
        mn = new javax.swing.JButton();
        me = new javax.swing.JButton();
        ms = new javax.swing.JButton();
        mu = new javax.swing.JButton();
        mi = new javax.swing.JButton();
        mc = new javax.swing.JButton();
        md = new javax.swing.JButton();
        mt = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jl_p = new javax.swing.JList<>();
        jLabel25 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        jl_a = new javax.swing.JList<>();
        jLabel26 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane13 = new javax.swing.JScrollPane();
        block = new javax.swing.JList<>();
        jButton9 = new javax.swing.JButton();
        jLabel31 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane9 = new javax.swing.JScrollPane();
        jl_x = new javax.swing.JList<>();
        jLabel27 = new javax.swing.JLabel();
        bt_mirar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane10 = new javax.swing.JScrollPane();
        jl_mensajes = new javax.swing.JList<>();
        jLabel28 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane11 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel29 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane12 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jLabel30 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        modificardescripcion = new javax.swing.JDialog();
        jLabel23 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        ta_de = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        modificarintereses = new javax.swing.JDialog();
        jLabel24 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        ta_de1 = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tf_iu = new javax.swing.JTextField();
        tf_ip = new javax.swing.JPasswordField();
        bt_iniciar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        bt_registrarse = new javax.swing.JButton();

        jd_registrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jd_registrarMouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("Registro");

        jLabel6.setText("Nombre");

        jLabel7.setText("Edad");

        sp_edad.setModel(new javax.swing.SpinnerNumberModel(0, null, 100, 1));

        bt_sexo.add(bt_m);
        bt_m.setSelected(true);
        bt_m.setText("M");

        bt_sexo.add(bt_f);
        bt_f.setText("F");

        jLabel8.setText("Sexo");

        jLabel9.setText("Usuario");

        jLabel10.setText("Contraseña");

        jLabel11.setText("Descripcion");

        ta_descripcion.setColumns(20);
        ta_descripcion.setRows(5);
        jScrollPane1.setViewportView(ta_descripcion);

        jLabel12.setText("¿Premium?");

        bg_premium.add(bg_si);
        bg_si.setSelected(true);
        bg_si.setText("Si");

        bg_premium.add(bg_no);
        bg_no.setText("No");

        jLabel13.setText("Intereses");

        ta_intereses.setColumns(20);
        ta_intereses.setRows(5);
        jScrollPane2.setViewportView(ta_intereses);

        bt_registrar.setText("Registrar");
        bt_registrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_registrarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_registrarLayout = new javax.swing.GroupLayout(jd_registrar.getContentPane());
        jd_registrar.getContentPane().setLayout(jd_registrarLayout);
        jd_registrarLayout.setHorizontalGroup(
            jd_registrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_registrarLayout.createSequentialGroup()
                .addGroup(jd_registrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_registrarLayout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addComponent(jLabel5))
                    .addGroup(jd_registrarLayout.createSequentialGroup()
                        .addGroup(jd_registrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jd_registrarLayout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addGroup(jd_registrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_registrarLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jd_registrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jd_registrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(reg_nombre)
                            .addComponent(sp_edad, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jd_registrarLayout.createSequentialGroup()
                                .addComponent(bt_m)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bt_f))
                            .addComponent(reg_usuario)
                            .addComponent(reg_contraseña)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
                            .addGroup(jd_registrarLayout.createSequentialGroup()
                                .addComponent(bg_si)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bg_no))
                            .addComponent(jScrollPane2)))
                    .addGroup(jd_registrarLayout.createSequentialGroup()
                        .addGap(212, 212, 212)
                        .addComponent(bt_registrar)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jd_registrarLayout.setVerticalGroup(
            jd_registrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_registrarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(jd_registrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(reg_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_registrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(sp_edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_registrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_m)
                    .addComponent(bt_f)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jd_registrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(reg_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_registrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(reg_contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_registrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                .addGroup(jd_registrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(bg_si)
                    .addComponent(bg_no))
                .addGap(18, 18, 18)
                .addGroup(jd_registrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(bt_registrar)
                .addGap(25, 25, 25))
        );

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel14.setText("Bienvenido");

        tab.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tab.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tabStateChanged(evt);
            }
        });

        jLabel15.setText("Nombre Completo");

        jLabel16.setText("Edad");

        jLabel17.setText("Sexo");

        jLabel18.setText("Usuario");

        jLabel19.setText("Contraseña");

        jLabel20.setText("Intereses");

        mostrarn.setEditable(false);

        mostrare.setEditable(false);

        mostrars.setEditable(false);
        mostrars.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarsActionPerformed(evt);
            }
        });

        mostraru.setEditable(false);
        mostraru.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mostraruMouseClicked(evt);
            }
        });
        mostraru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostraruActionPerformed(evt);
            }
        });

        mostrarc.setEditable(false);
        mostrarc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarcActionPerformed(evt);
            }
        });

        mostrari.setEditable(false);
        mostrari.setColumns(20);
        mostrari.setRows(5);
        jScrollPane3.setViewportView(mostrari);

        jLabel21.setText("Descripcion");

        mostrard.setEditable(false);
        mostrard.setColumns(20);
        mostrard.setRows(5);
        jScrollPane4.setViewportView(mostrard);

        jLabel22.setText("Tipo");

        mostrart.setEditable(false);

        mn.setText("Modificar");
        mn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnMouseClicked(evt);
            }
        });

        me.setText("Modificar");
        me.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                meMouseClicked(evt);
            }
        });

        ms.setText("Modificar");
        ms.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                msMouseClicked(evt);
            }
        });

        mu.setText("Modificar");

        mi.setText("Modificar");
        mi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                miMouseClicked(evt);
            }
        });

        mc.setText("Modificar");
        mc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mcMouseClicked(evt);
            }
        });

        md.setText("Modificar");
        md.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mdMouseClicked(evt);
            }
        });

        mt.setText("Modificar");
        mt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mtMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel21)
                    .addComponent(jLabel20)
                    .addComponent(jLabel19)
                    .addComponent(jLabel18)
                    .addComponent(jLabel17)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(mostrare, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(me))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(mostrars, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ms))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(mostraru, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mu))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(mostrarc, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mc))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 371, Short.MAX_VALUE)
                            .addComponent(jScrollPane4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mi)
                            .addComponent(md)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(mostrarn, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mostrart, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mt)))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(mostrarn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(mostrart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mn)
                    .addComponent(mt))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(mostrare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(me))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(mostrars, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ms))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(mostraru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mu))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(mostrarc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mc))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(mi)
                        .addGap(85, 85, 85)
                        .addComponent(md)
                        .addGap(67, 67, 67))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27))))
        );

        tab.addTab("Inicio", jPanel1);

        jl_p.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jl_p.setModel(new DefaultListModel());
        jScrollPane7.setViewportView(jl_p);

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel25.setText("Lista de personas");

        jl_a.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jl_a.setModel(new DefaultListModel());
        jScrollPane8.setViewportView(jl_a);

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel26.setText("Lista actual de amigos");

        jButton3.setText("Agregar a amigos");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel26)
                .addGap(100, 100, 100))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(jLabel26))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 409, Short.MAX_VALUE)
                            .addComponent(jScrollPane7))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addGap(199, 199, 199))))
        );

        tab.addTab("Agregar amigos", jPanel2);

        block.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        block.setModel(new DefaultListModel());
        jScrollPane13.setViewportView(block);

        jButton9.setText("Bloquear (Seleccione primero de la lista)");

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel31.setText("Perfiles");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
                .addGap(36, 36, 36))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addComponent(jLabel31)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jLabel31)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(189, 189, 189)
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tab.addTab("Bloquear usuario", jPanel6);

        jl_x.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jl_x.setModel(new DefaultListModel());
        jScrollPane9.setViewportView(jl_x);

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel27.setText("Usuarios");

        bt_mirar.setText("Mirar perfil");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bt_mirar))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(341, 341, 341)
                        .addComponent(jLabel27)))
                .addContainerGap(133, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane9)
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(bt_mirar)
                        .addContainerGap(232, Short.MAX_VALUE))))
        );

        tab.addTab("Ver perfiles", jPanel3);

        jl_mensajes.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jl_mensajes.setModel(new DefaultListModel());
        jScrollPane10.setViewportView(jl_mensajes);

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel28.setText("Amigos");

        jButton4.setText("Enviar mensaje (Seleccione primero de la lista)");

        jButton5.setText("Ver mensajes recibidos");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(jLabel28)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(48, 48, 48))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel28)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        tab.addTab("Ver/Enviar mensaje", jPanel4);

        jList1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jList1.setModel(new DefaultListModel());
        jScrollPane11.setViewportView(jList1);

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel29.setText("Calendario");

        jButton6.setText("Crear cita (Seleccione primero de la lista)");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(jLabel29)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel29)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        tab.addTab("Calendario", jPanel7);

        jPanel5.setEnabled(false);

        jList2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jList2.setModel(new DefaultListModel());
        jScrollPane12.setViewportView(jList2);

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel30.setText("Usuarios con intereses en comun");

        jButton7.setText("Ver perfil (Seleccione primero de la lista)");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67)
                        .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jLabel30)))
                .addGap(71, 71, 71))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel30)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        tab.addTab("Usuarios Intereses(Solo premium)", jPanel5);

        javax.swing.GroupLayout jd_usuarioLayout = new javax.swing.GroupLayout(jd_usuario.getContentPane());
        jd_usuario.getContentPane().setLayout(jd_usuarioLayout);
        jd_usuarioLayout.setHorizontalGroup(
            jd_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_usuarioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addGap(332, 332, 332))
            .addGroup(jd_usuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tab)
                .addContainerGap())
        );
        jd_usuarioLayout.setVerticalGroup(
            jd_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_usuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tab)
                .addContainerGap())
        );

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel23.setText("Ingrese su nueva descripcion");

        ta_de.setColumns(20);
        ta_de.setRows(5);
        jScrollPane5.setViewportView(ta_de);

        jButton1.setText("Aceptar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout modificardescripcionLayout = new javax.swing.GroupLayout(modificardescripcion.getContentPane());
        modificardescripcion.getContentPane().setLayout(modificardescripcionLayout);
        modificardescripcionLayout.setHorizontalGroup(
            modificardescripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modificardescripcionLayout.createSequentialGroup()
                .addGroup(modificardescripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(modificardescripcionLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane5))
                    .addGroup(modificardescripcionLayout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(jLabel23)
                        .addGap(0, 148, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, modificardescripcionLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(265, 265, 265))
        );
        modificardescripcionLayout.setVerticalGroup(
            modificardescripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modificardescripcionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel23)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(27, 27, 27))
        );

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel24.setText("Intereses");

        ta_de1.setColumns(20);
        ta_de1.setRows(5);
        jScrollPane6.setViewportView(ta_de1);

        jButton2.setText("Aceptar");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout modificarinteresesLayout = new javax.swing.GroupLayout(modificarintereses.getContentPane());
        modificarintereses.getContentPane().setLayout(modificarinteresesLayout);
        modificarinteresesLayout.setHorizontalGroup(
            modificarinteresesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modificarinteresesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(modificarinteresesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(modificarinteresesLayout.createSequentialGroup()
                        .addComponent(jScrollPane6)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, modificarinteresesLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(183, 183, 183))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, modificarinteresesLayout.createSequentialGroup()
                .addContainerGap(196, Short.MAX_VALUE)
                .addComponent(jLabel24)
                .addGap(176, 176, 176))
        );
        modificarinteresesLayout.setVerticalGroup(
            modificarinteresesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modificarinteresesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel24)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jButton8.setText("Ver perfil (Seleccione primero de la lista)");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Tander");

        jLabel2.setText("Usuario");

        jLabel3.setText("Contraseña");

        bt_iniciar.setText("Iniciar sesión");
        bt_iniciar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_iniciarMouseClicked(evt);
            }
        });

        jLabel4.setText("¿No tienes cuenta? ¡Registrate aquí!");

        bt_registrarse.setText("Registrarse");
        bt_registrarse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_registrarseMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_iu, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_ip, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_registrarse))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(bt_iniciar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tf_iu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tf_ip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(bt_iniciar)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(bt_registrarse))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_registrarseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_registrarseMouseClicked
        // TODO add your handling code here:
        jd_registrar.setModal(true);
        jd_registrar.pack();
        jd_registrar.setLocationRelativeTo(this);
        jd_registrar.setVisible(true);
    }//GEN-LAST:event_bt_registrarseMouseClicked

    private void jd_registrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jd_registrarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jd_registrarMouseClicked

    private void bt_registrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_registrarMouseClicked
        // TODO add your handling code here:
        try {
//            administrarUsuarios ap = new administrarUsuarios("./Usuarios.ella");
//            ap.cargarArchivo();
            if ("".equals(reg_nombre.getText()) || (Integer) sp_edad.getValue() < 18 || "".equals(reg_usuario.getText()) || "".equals(reg_contraseña.getText()) || "".equals(ta_descripcion.getText()) || "".equals(ta_intereses.getText())) {
                JOptionPane.showMessageDialog(jd_registrar, "Lo siento, campo vacio o edad menor que 18");
            } else {
                String[] intereses = ta_intereses.getText().split(",");
                if (intereses.length >= 10) {
                    String sexo = "", tipo = "";
                    if (bt_m.isSelected()) {
                        sexo = "Masculino";
                    } else {
                        sexo = "Femenino";
                    }
                    if (bg_si.isSelected()) {
                        tipo = "Premium";
                    } else {
                        tipo = "No Premium";
                    }
                    ArrayList tempo = new ArrayList();
                    for (int i = 0; i < intereses.length; i++) {
                        tempo.add(intereses[i]);
                    }
//                    Usuarios u = new Usuarios(reg_nombre.getText(), (Integer) sp_edad.getValue(), sexo, reg_usuario.getText(), reg_contraseña.getText(), ta_descripcion.getText(), tipo);
//                    u.setIntereses(tempo);
                    administrarUsuarios ap = new administrarUsuarios("./Usuarios.ella");
                    ap.cargarArchivo();
                    int valid = 0;
                    for (Usuarios t : ap.getListaUsuarios()) {
                        if (reg_usuario.getText().equals(t.getUsuario())) {
                            valid++;
                        } else {
                            
                        }
                    }
                    if (valid == 0) {
                        Usuarios u = new Usuarios(reg_nombre.getText(), (Integer) sp_edad.getValue(), sexo, reg_usuario.getText(), reg_contraseña.getText(), ta_descripcion.getText(), tipo);
                        u.setIntereses(tempo);
                        ap.setListaUsuario(u);
                        ap.escribirArchivo();
                        JOptionPane.showMessageDialog(jd_registrar, "Usuario registrado con exito");
                        reg_nombre.setText("");
                        reg_usuario.setText("");
                        reg_contraseña.setText("");
                        ta_descripcion.setText("");
                        ta_intereses.setText("");
                        jd_registrar.setVisible(false);
                    } else {
                        JOptionPane.showMessageDialog(jd_registrar, "Error, usuario ya existe");
                    }
                } else {
                    JOptionPane.showMessageDialog(jd_registrar, "Lo siento, faltan mas intereses y/o espacios");
                }
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_bt_registrarMouseClicked

    private void bt_iniciarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_iniciarMouseClicked
        // TODO add your handling code here:
        try {
            administrarUsuarios ap = new administrarUsuarios("./Usuarios.ella");
            ap.cargarArchivo();
            for (Usuarios t : ap.getListaUsuarios()) {
                if (tf_iu.getText().equals(t.getUsuario()) && tf_ip.getText().equals(t.getContraseña())) {
                    mostrarn.setText(t.getNombre());
                    mostrare.setText(Integer.toString(t.getEdad()));
                    mostrars.setText(t.getSexo());
                    mostraru.setText(t.getUsuario());
                    mostrarc.setText(t.getContraseña());
                    mostrard.setText(t.getDescripcion());
                    mostrari.setText(t.getIntereses().toString());
                    if (t.getTipo().equals("Premium")) {
                        jPanel5.setEnabled(true);
                        tab.getSelectedComponent().setEnabled(true);
                        mostrart.setText(t.getTipo());
                    } else {
                        jPanel5.setEnabled(false);
                        jPanel5.setVisible(false);
                        tab.getSelectedComponent().setEnabled(false);
                        tab.getComponentAt(6).setEnabled(false);
                        mostrart.setText(t.getTipo());
                    }
                    JOptionPane.showMessageDialog(this, "Inicio exitoso");
                    jd_usuario.setModal(true);
                    jd_usuario.pack();
                    jd_usuario.setLocationRelativeTo(this);
                    jd_usuario.setVisible(true);
                }
            }
            ap.escribirArchivo();
        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_bt_iniciarMouseClicked

    private void mostrarsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mostrarsActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void mostraruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostraruActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mostraruActionPerformed

    private void mostrarcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mostrarcActionPerformed

    private void mnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnMouseClicked
        // TODO add your handling code here:
        administrarUsuarios ap = new administrarUsuarios("./Usuarios.ella");
        ap.cargarArchivo();
        for (Usuarios t : ap.getListaUsuarios()) {
            if (tf_iu.getText().equals(t.getUsuario()) && tf_ip.getText().equals(t.getContraseña())) {
                t.setNombre(JOptionPane.showInputDialog(jd_usuario, "Ingrese el nuevo nombre"));
                mostrarn.setText(t.getNombre());
                JOptionPane.showMessageDialog(jd_usuario, "Modificado con exito");
            }
        }
        ap.escribirArchivo();
    }//GEN-LAST:event_mnMouseClicked

    private void meMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_meMouseClicked
        // TODO add your handling code here:
        administrarUsuarios ap = new administrarUsuarios("./Usuarios.ella");
        ap.cargarArchivo();
        for (Usuarios t : ap.getListaUsuarios()) {
            if (tf_iu.getText().equals(t.getUsuario()) && tf_ip.getText().equals(t.getContraseña())) {
                t.setEdad(Integer.parseInt(JOptionPane.showInputDialog(jd_usuario, "Ingrese la nueva edad")));
                mostrare.setText(Integer.toString(t.getEdad()));
                JOptionPane.showMessageDialog(jd_usuario, "Modificado con exito");
            }
        }
        ap.escribirArchivo();
    }//GEN-LAST:event_meMouseClicked

    private void msMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_msMouseClicked
        // TODO add your handling code here:
        administrarUsuarios ap = new administrarUsuarios("./Usuarios.ella");
        ap.cargarArchivo();
        for (Usuarios t : ap.getListaUsuarios()) {
            if (tf_iu.getText().equals(t.getUsuario()) && tf_ip.getText().equals(t.getContraseña())) {
                t.setSexo(JOptionPane.showInputDialog(jd_usuario, "Ingrese el nuevo sexo"));
                mostrars.setText(t.getSexo());
                JOptionPane.showMessageDialog(jd_usuario, "Modificado con exito");
            }
        }
        ap.escribirArchivo();
    }//GEN-LAST:event_msMouseClicked

    private void mostraruMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mostraruMouseClicked
        // TODO add your handling code here:
        administrarUsuarios ap = new administrarUsuarios("./Usuarios.ella");
        ap.cargarArchivo();
        for (Usuarios t : ap.getListaUsuarios()) {
            if (tf_iu.getText().equals(t.getUsuario()) && tf_ip.getText().equals(t.getContraseña())) {
                t.setUsuario(JOptionPane.showInputDialog(jd_usuario, "Ingrese el nuevo usuario"));
                mostraru.setText(t.getUsuario());
                JOptionPane.showMessageDialog(jd_usuario, "Modificado con exito");
            }
        }
        ap.escribirArchivo();
    }//GEN-LAST:event_mostraruMouseClicked

    private void mcMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mcMouseClicked
        // TODO add your handling code here:
        administrarUsuarios ap = new administrarUsuarios("./Usuarios.ella");
        ap.cargarArchivo();
        for (Usuarios t : ap.getListaUsuarios()) {
            if (tf_iu.getText().equals(t.getUsuario()) && tf_ip.getText().equals(t.getContraseña())) {
                t.setContraseña(JOptionPane.showInputDialog(jd_usuario, "Ingrese la nueva contraseña"));
                mostrarc.setText(t.getContraseña());
                JOptionPane.showMessageDialog(jd_usuario, "Modificado con exito");
            }
        }
        ap.escribirArchivo();
    }//GEN-LAST:event_mcMouseClicked

    private void mtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mtMouseClicked
        // TODO add your handling code here:
        administrarUsuarios ap = new administrarUsuarios("./Usuarios.ella");
        ap.cargarArchivo();
        for (Usuarios t : ap.getListaUsuarios()) {
            if (tf_iu.getText().equals(t.getUsuario()) && tf_ip.getText().equals(t.getContraseña())) {
                t.setTipo(JOptionPane.showInputDialog(jd_usuario, "Ingrese el nuevo tipo"));
                mostrart.setText(t.getTipo());
                JOptionPane.showMessageDialog(jd_usuario, "Modificado con exito");
            }
        }
        ap.escribirArchivo();
    }//GEN-LAST:event_mtMouseClicked

    private void miMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miMouseClicked
        // TODO add your handling code here:
        ta_de1.setText(mostrari.getText());
        modificarintereses.setModal(true);
        modificarintereses.pack();
        modificarintereses.setLocationRelativeTo(this);
        modificarintereses.setVisible(true);
    }//GEN-LAST:event_miMouseClicked

    private void mdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mdMouseClicked
        // TODO add your handling code here:
        modificardescripcion.setModal(true);
        modificardescripcion.pack();
        modificardescripcion.setLocationRelativeTo(this);
        modificardescripcion.setVisible(true);
    }//GEN-LAST:event_mdMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        administrarUsuarios ap = new administrarUsuarios("./Usuarios.ella");
        ap.cargarArchivo();
        for (Usuarios t : ap.getListaUsuarios()) {
            if (tf_iu.getText().equals(t.getUsuario()) && tf_ip.getText().equals(t.getContraseña())) {
                t.setDescripcion(ta_de.getText());
                mostrard.setText(t.getDescripcion());
                JOptionPane.showMessageDialog(jd_usuario, "Modificado con exito");
            }
        }
        modificardescripcion.setVisible(false);
        ap.escribirArchivo();
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        administrarUsuarios ap = new administrarUsuarios("./Usuarios.ella");
        ap.cargarArchivo();
        for (Usuarios t : ap.getListaUsuarios()) {
            if (tf_iu.getText().equals(t.getUsuario()) && tf_ip.getText().equals(t.getContraseña())) {
                String[] intereses = ta_de1.getText().split(",");
                if (intereses.length >= 10) {
                    ArrayList tempo = new ArrayList();
                    for (int i = 0; i < intereses.length; i++) {
                        tempo.add(intereses[i]);
                    }
                    t.setIntereses(tempo);
                    mostrari.setText(t.getIntereses().toString());
                    JOptionPane.showMessageDialog(jd_usuario, "Modificado con exito");
                } else {
                    JOptionPane.showMessageDialog(jd_usuario, "Error, tienen que ser mas de 10 intereses");
                }
                
            }
        }
        modificarintereses.setVisible(false);
        ap.escribirArchivo();
    }//GEN-LAST:event_jButton2MouseClicked

    private void tabStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tabStateChanged
        // TODO add your handling code here:
        try {
            if (tab.getSelectedIndex() == 1) {
                administrarUsuarios ap = new administrarUsuarios("./Usuarios.ella");
                ap.cargarArchivo();
                DefaultListModel m = (DefaultListModel) jl_p.getModel();
                m.removeAllElements();
                for (int i = 0; i < ap.getListaUsuarios().size(); i++) {
                    if (tf_iu.getText().equals(ap.getListaUsuarios().get(i).getUsuario()) && tf_ip.getText().equals(ap.getListaUsuarios().get(i).getContraseña())) {
                        
                    } else {
                        m.addElement(ap.getListaUsuarios().get(i));
                    }
                }
                jl_p.setModel(m);
                DefaultListModel m2 = (DefaultListModel) jl_a.getModel();
                m2.removeAllElements();
                for (int j = 0; j < ap.getListaUsuarios().size(); j++) {
                    if (tf_iu.getText().equals(ap.getListaUsuarios().get(j).getUsuario()) && tf_ip.getText().equals(ap.getListaUsuarios().get(j).getContraseña())) {
                        for (int i = 0; i < ap.getListaUsuarios().get(j).getAmigos().size(); i++) {
                            m2.addElement(ap.getListaUsuarios().get(j).getAmigos().get(i));
                        }
                    }
                }
                jl_a.setModel(m2);
                ap.escribirArchivo();
            }
            if (tab.getSelectedIndex() == 2) {
                administrarUsuarios ap = new administrarUsuarios("./Usuarios.ella");
                ap.cargarArchivo();
                DefaultListModel m = (DefaultListModel) block.getModel();
                m.removeAllElements();
                for (int i = 0; i < ap.getListaUsuarios().size(); i++) {
                    if (tf_iu.getText().equals(ap.getListaUsuarios().get(i).getUsuario()) && tf_ip.getText().equals(ap.getListaUsuarios().get(i).getContraseña())) {
                        
                    } else {
                        m.addElement(ap.getListaUsuarios().get(i));
                    }
                }
                block.setModel(m);
            }
            if (tab.getSelectedIndex() == 3) {
                administrarUsuarios ap = new administrarUsuarios("./Usuarios.ella");
                ap.cargarArchivo();
                DefaultListModel m = (DefaultListModel) jl_x.getModel();
                m.removeAllElements();
                for (int i = 0; i < ap.getListaUsuarios().size(); i++) {
                    if (tf_iu.getText().equals(ap.getListaUsuarios().get(i).getUsuario()) && tf_ip.getText().equals(ap.getListaUsuarios().get(i).getContraseña())) {
                        
                    } else {
                        m.addElement(ap.getListaUsuarios().get(i));
                    }
                }
                jl_x.setModel(m);
                ap.escribirArchivo();
            }
            if (tab.getSelectedIndex() == 4) {
                DefaultListModel m = (DefaultListModel) jl_mensajes.getModel();
                m.removeAllElements();
                administrarUsuarios ap = new administrarUsuarios("./Usuarios.ella");
                ap.cargarArchivo();
                for (int j = 0; j < ap.getListaUsuarios().size(); j++) {
                    if (tf_iu.getText().equals(ap.getListaUsuarios().get(j).getUsuario()) && tf_ip.getText().equals(ap.getListaUsuarios().get(j).getContraseña())) {
                        for (int i = 0; i < ap.getListaUsuarios().get(j).getAmigos().size(); i++) {
                            m.addElement(ap.getListaUsuarios().get(j).getAmigos().get(i));
                        }
                    }
                }
                jl_mensajes.setModel(m);
                ap.escribirArchivo();
            }
            if (tab.getSelectedIndex() == 5) {
                
            }
            if (tab.getSelectedIndex() == 6) {
                
            }            
        } catch (Exception e) {
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_tabStateChanged

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        try {
            if (jl_p.getSelectedIndex() >= 0) {
                DefaultListModel m = (DefaultListModel) jl_p.getModel();
                DefaultListModel m2 = (DefaultListModel) jl_a.getModel();
                String nombre, sexo, usuario, contraseña, descripcion, tipo;
                int edad;
                nombre = ((Usuarios) m.get(jl_p.getSelectedIndex())).getNombre();
                edad = ((Usuarios) m.get(jl_p.getSelectedIndex())).getEdad();
                sexo = ((Usuarios) m.get(jl_p.getSelectedIndex())).getSexo();
                usuario = ((Usuarios) m.get(jl_p.getSelectedIndex())).getUsuario();
                contraseña = ((Usuarios) m.get(jl_p.getSelectedIndex())).getContraseña();
                descripcion = ((Usuarios) m.get(jl_p.getSelectedIndex())).getDescripcion();
                tipo = ((Usuarios) m.get(jl_p.getSelectedIndex())).getTipo();
                ArrayList intereses = new ArrayList();
                ArrayList<Usuarios> amigos = new ArrayList();
                ArrayList<Usuarios> interesados = new ArrayList();
                ArrayList<mensajes> mensajes = new ArrayList();
                ArrayList<Usuarios> solicitudes = new ArrayList();
                ArrayList<Usuarios> bloqueados = new ArrayList();
                ArrayList<Calendario> citas = new ArrayList();
                Usuarios u = new Usuarios(nombre, edad, sexo, usuario, contraseña, descripcion, tipo);
                u.setAmigos(amigos);
                u.setIntereses(intereses);
                u.setInteresados(interesados);
                u.setMensajes(mensajes);
                u.setBloqueados(bloqueados);
                u.setSolicitudes(solicitudes);
                u.setCitas(citas);
                administrarUsuarios ap = new administrarUsuarios("./Usuarios.ella");
                ap.cargarArchivo();
                //   for (Usuarios t : ap.getListaUsuarios()) {
                for (int i = 0; i < ap.getListaUsuarios().size(); i++) {
                    if (tf_iu.getText().equals(ap.getListaUsuarios().get(i).getUsuario()) && tf_ip.getText().equals(ap.getListaUsuarios().get(i).getContraseña())) {
                        ap.getListaUsuarios().get(i).getAmigos().add(u);
                        ap.escribirArchivo();
                        m2.addElement(ap.getListaUsuarios().get(i).getAmigos().get(ap.getListaUsuarios().get(i).getAmigos().size() - 1));
                    }
                }
                ap.escribirArchivo();
                jl_a.setModel(m2);
                m.remove(jl_p.getSelectedIndex());
                jl_p.setModel(m);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton3MouseClicked

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        administrarUsuarios ap = new administrarUsuarios("./Usuarios.ella");
        ap.cargarArchivo();
        ap.escribirArchivo();
        JOptionPane.showMessageDialog(this, "Adios");
        System.exit(0);
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        administrarUsuarios ap = new administrarUsuarios("./Usuarios.ella");
        ap.cargarArchivo();
        ap.escribirArchivo();
        JOptionPane.showMessageDialog(this, "Adios, archivo guardado con exito");
        System.exit(0);
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton bg_no;
    private javax.swing.ButtonGroup bg_premium;
    private javax.swing.JRadioButton bg_si;
    private javax.swing.JList<String> block;
    private javax.swing.JRadioButton bt_f;
    private javax.swing.JButton bt_iniciar;
    private javax.swing.JRadioButton bt_m;
    private javax.swing.JButton bt_mirar;
    private javax.swing.JButton bt_registrar;
    private javax.swing.JButton bt_registrarse;
    private javax.swing.ButtonGroup bt_sexo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JDialog jd_registrar;
    private javax.swing.JDialog jd_usuario;
    private javax.swing.JList<String> jl_a;
    private javax.swing.JList<String> jl_mensajes;
    private javax.swing.JList<String> jl_p;
    private javax.swing.JList<String> jl_x;
    private javax.swing.JButton mc;
    private javax.swing.JButton md;
    private javax.swing.JButton me;
    private javax.swing.JButton mi;
    private javax.swing.JButton mn;
    private javax.swing.JDialog modificardescripcion;
    private javax.swing.JDialog modificarintereses;
    private javax.swing.JTextField mostrarc;
    private javax.swing.JTextArea mostrard;
    private javax.swing.JTextField mostrare;
    private javax.swing.JTextArea mostrari;
    private javax.swing.JTextField mostrarn;
    private javax.swing.JTextField mostrars;
    private javax.swing.JTextField mostrart;
    private javax.swing.JTextField mostraru;
    private javax.swing.JButton ms;
    private javax.swing.JButton mt;
    private javax.swing.JButton mu;
    private javax.swing.JTextField reg_contraseña;
    private javax.swing.JTextField reg_nombre;
    private javax.swing.JTextField reg_usuario;
    private javax.swing.JSpinner sp_edad;
    private javax.swing.JTextArea ta_de;
    private javax.swing.JTextArea ta_de1;
    private javax.swing.JTextArea ta_descripcion;
    private javax.swing.JTextArea ta_intereses;
    private javax.swing.JTabbedPane tab;
    private javax.swing.JPasswordField tf_ip;
    private javax.swing.JTextField tf_iu;
    // End of variables declaration//GEN-END:variables
}
